.TH UCHARDET "1" "July 2011" "uchardet " "User Commands"
.SH NAME
uchardet \- universalchardet (Universal Charset Detector)
.SH DESCRIPTION
uchardet Command Line Tool
.SS "Usage:"
.HP
uchardet [\fBOptions\fR] [\fBFile\fR]...
.HP
\fB\-v\fR
Print version and build information.
.HP
\fB\-h\fR
Print help text.
.HP
.IP
.PP
uchardet Command Line Tool
